Add snakefmt tool into the lint target
* Tipo correction on the version

* Increase version

* Add snakefmt tool in the lint target

- Add snakefmt requirement and command into the lint target of tox.ini
- Reformat archngv/app/snakemake/Snakefile with snakefmt
- Move release form 2023-03 to 2023-05 because of libsonata issue:
      -> from libsonata import CircuitConfigStatus ImportError: cannot import name 'CircuitConfigStatus' from 'libsonata'